import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { LocalizationProvider } from "@frontifyHub/common/localization";
import { ChakraProvider, ColorModeScript } from "@chakra-ui/react";
import theme from "./theme";
import "./globals.css";
import Header from "../components/templates/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider theme={theme}>
          <LocalizationProvider>
            <Header />
            {children}
          </LocalizationProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import ClientLayout from "../components/templates/ClientLayout";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body>
//         <ClientLayout>{children}</ClientLayout>
//       </body>
//     </html>
//   );
// }
