import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { LocalizationProvider } from "@frontifyHub/common/localization";
import { ChakraProvider, ColorModeScript } from "@chakra-ui/react";
import theme from "./theme";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider theme={theme}>
          <LocalizationProvider>{children}</LocalizationProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}